version: '3.4'

services:

  joiner:
    image: ${DOCKER_REGISTRY-}csharprover
    build:
      context: .
      dockerfile: console/Dockerfile
    command: ["-u $URL", "-g$GAMEID", "-m $MAXTEAMS", "-n joiner"]
    network_mode: "host"
    volumes:
      - ./maps:/maps
      - ./joined:/joined

  straight:
    image: ${DOCKER_REGISTRY-}csharprover
    build:
      context: .
      dockerfile: console/Dockerfile
    command: ["-u $URL", "-g$GAMEID", "-q", "-m $MAXTEAMS", "-n straight"]
    network_mode: "host"
    volumes:
      - ./maps:/maps
      - ./joined:/joined
    depends_on:
      - joiner
  quick:
    image: ${DOCKER_REGISTRY-}csharprover
    build:
      context: .
      dockerfile: console/Dockerfile
    command: ["-u $URL", "-g$GAMEID", "-o 1", "-s 200", "-m $MAXTEAMS", "-n quick"]
    network_mode: "host"
    volumes:
      - ./maps:/maps
      - ./joined:/joined
    depends_on:
      - joiner
  smart:
    image: ${DOCKER_REGISTRY-}csharprover
    build:
      context: .
      dockerfile: console/Dockerfile
    command: ["-u $URL", "-g$GAMEID", "-m $MAXTEAMS", "-n smart"]
    network_mode: "host"
    volumes:
      - ./maps:/maps
      - ./joined:/joined
    depends_on:
      - joiner

