version: '3.4'

services:
  straight:
    image: ${DOCKER_REGISTRY-}csharprover
    build:
      context: .
      dockerfile: console/Dockerfile
    command: ["-u $URL", "-g$GAMEID", "-q", "-m $MAXTEAMS"]
    network_mode: "host"
    volumes:
      - ./maps:/maps

  quick:
    image: ${DOCKER_REGISTRY-}csharprover
    build:
      context: .
      dockerfile: console/Dockerfile
    command: ["-u $URL", "-g$GAMEID", "-o 1", "-s 200", "-m $MAXTEAMS"]
    network_mode: "host"
    volumes:
      - ./maps:/maps
  smart:
    image: ${DOCKER_REGISTRY-}csharprover
    build:
      context: .
      dockerfile: console/Dockerfile
    command: ["-u $URL", "-g$GAMEID", "-m $MAXTEAMS"]
    network_mode: "host"
    volumes:
      - ./maps:/maps
