name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: 40.90.192.95
        username: cwighty
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./"
        target: "/home/cwighty/rover"
